// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/mblock/commands.proto

package com.alexkorovyansky.mblock.proto;

public final class MbLockCommands {
  private MbLockCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .mblock.Request.Type type = 1;
    /**
     * <code>required .mblock.Request.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .mblock.Request.Type type = 1;</code>
     */
    com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type getType();

    // optional .mblock.Open open = 2;
    /**
     * <code>optional .mblock.Open open = 2;</code>
     */
    boolean hasOpen();
    /**
     * <code>optional .mblock.Open open = 2;</code>
     */
    com.alexkorovyansky.mblock.proto.MbLockCommands.Open getOpen();
    /**
     * <code>optional .mblock.Open open = 2;</code>
     */
    com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder getOpenOrBuilder();

    // optional .mblock.Close close = 3;
    /**
     * <code>optional .mblock.Close close = 3;</code>
     */
    boolean hasClose();
    /**
     * <code>optional .mblock.Close close = 3;</code>
     */
    com.alexkorovyansky.mblock.proto.MbLockCommands.Close getClose();
    /**
     * <code>optional .mblock.Close close = 3;</code>
     */
    com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder getCloseOrBuilder();
  }
  /**
   * Protobuf type {@code mblock.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type value = com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = open_.toBuilder();
              }
              open_ = input.readMessage(com.alexkorovyansky.mblock.proto.MbLockCommands.Open.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(open_);
                open_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = close_.toBuilder();
              }
              close_ = input.readMessage(com.alexkorovyansky.mblock.proto.MbLockCommands.Close.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(close_);
                close_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexkorovyansky.mblock.proto.MbLockCommands.Request.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code mblock.Request.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OPEN = 1;</code>
       */
      OPEN(0, 1),
      /**
       * <code>CLOSE = 2;</code>
       */
      CLOSE(1, 2),
      ;

      /**
       * <code>OPEN = 1;</code>
       */
      public static final int OPEN_VALUE = 1;
      /**
       * <code>CLOSE = 2;</code>
       */
      public static final int CLOSE_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return OPEN;
          case 2: return CLOSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mblock.Request.Type)
    }

    private int bitField0_;
    // required .mblock.Request.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type type_;
    /**
     * <code>required .mblock.Request.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .mblock.Request.Type type = 1;</code>
     */
    public com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type getType() {
      return type_;
    }

    // optional .mblock.Open open = 2;
    public static final int OPEN_FIELD_NUMBER = 2;
    private com.alexkorovyansky.mblock.proto.MbLockCommands.Open open_;
    /**
     * <code>optional .mblock.Open open = 2;</code>
     */
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .mblock.Open open = 2;</code>
     */
    public com.alexkorovyansky.mblock.proto.MbLockCommands.Open getOpen() {
      return open_;
    }
    /**
     * <code>optional .mblock.Open open = 2;</code>
     */
    public com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder getOpenOrBuilder() {
      return open_;
    }

    // optional .mblock.Close close = 3;
    public static final int CLOSE_FIELD_NUMBER = 3;
    private com.alexkorovyansky.mblock.proto.MbLockCommands.Close close_;
    /**
     * <code>optional .mblock.Close close = 3;</code>
     */
    public boolean hasClose() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .mblock.Close close = 3;</code>
     */
    public com.alexkorovyansky.mblock.proto.MbLockCommands.Close getClose() {
      return close_;
    }
    /**
     * <code>optional .mblock.Close close = 3;</code>
     */
    public com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder getCloseOrBuilder() {
      return close_;
    }

    private void initFields() {
      type_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type.OPEN;
      open_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance();
      close_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasOpen()) {
        if (!getOpen().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasClose()) {
        if (!getClose().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, open_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, close_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, open_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, close_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alexkorovyansky.mblock.proto.MbLockCommands.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mblock.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alexkorovyansky.mblock.proto.MbLockCommands.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alexkorovyansky.mblock.proto.MbLockCommands.Request.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Builder.class);
      }

      // Construct using com.alexkorovyansky.mblock.proto.MbLockCommands.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOpenFieldBuilder();
          getCloseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type.OPEN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (openBuilder_ == null) {
          open_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance();
        } else {
          openBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (closeBuilder_ == null) {
          close_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance();
        } else {
          closeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Request_descriptor;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Request getDefaultInstanceForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.Request.getDefaultInstance();
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Request build() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Request buildPartial() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Request result = new com.alexkorovyansky.mblock.proto.MbLockCommands.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (openBuilder_ == null) {
          result.open_ = open_;
        } else {
          result.open_ = openBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (closeBuilder_ == null) {
          result.close_ = close_;
        } else {
          result.close_ = closeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alexkorovyansky.mblock.proto.MbLockCommands.Request) {
          return mergeFrom((com.alexkorovyansky.mblock.proto.MbLockCommands.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alexkorovyansky.mblock.proto.MbLockCommands.Request other) {
        if (other == com.alexkorovyansky.mblock.proto.MbLockCommands.Request.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasOpen()) {
          mergeOpen(other.getOpen());
        }
        if (other.hasClose()) {
          mergeClose(other.getClose());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasOpen()) {
          if (!getOpen().isInitialized()) {
            
            return false;
          }
        }
        if (hasClose()) {
          if (!getClose().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alexkorovyansky.mblock.proto.MbLockCommands.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .mblock.Request.Type type = 1;
      private com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type type_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type.OPEN;
      /**
       * <code>required .mblock.Request.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .mblock.Request.Type type = 1;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type getType() {
        return type_;
      }
      /**
       * <code>required .mblock.Request.Type type = 1;</code>
       */
      public Builder setType(com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .mblock.Request.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Request.Type.OPEN;
        onChanged();
        return this;
      }

      // optional .mblock.Open open = 2;
      private com.alexkorovyansky.mblock.proto.MbLockCommands.Open open_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.alexkorovyansky.mblock.proto.MbLockCommands.Open, com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder, com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder> openBuilder_;
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.Open getOpen() {
        if (openBuilder_ == null) {
          return open_;
        } else {
          return openBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public Builder setOpen(com.alexkorovyansky.mblock.proto.MbLockCommands.Open value) {
        if (openBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          open_ = value;
          onChanged();
        } else {
          openBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public Builder setOpen(
          com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder builderForValue) {
        if (openBuilder_ == null) {
          open_ = builderForValue.build();
          onChanged();
        } else {
          openBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public Builder mergeOpen(com.alexkorovyansky.mblock.proto.MbLockCommands.Open value) {
        if (openBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              open_ != com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance()) {
            open_ =
              com.alexkorovyansky.mblock.proto.MbLockCommands.Open.newBuilder(open_).mergeFrom(value).buildPartial();
          } else {
            open_ = value;
          }
          onChanged();
        } else {
          openBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public Builder clearOpen() {
        if (openBuilder_ == null) {
          open_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance();
          onChanged();
        } else {
          openBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder getOpenBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getOpenFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder getOpenOrBuilder() {
        if (openBuilder_ != null) {
          return openBuilder_.getMessageOrBuilder();
        } else {
          return open_;
        }
      }
      /**
       * <code>optional .mblock.Open open = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.alexkorovyansky.mblock.proto.MbLockCommands.Open, com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder, com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder> 
          getOpenFieldBuilder() {
        if (openBuilder_ == null) {
          openBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.alexkorovyansky.mblock.proto.MbLockCommands.Open, com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder, com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder>(
                  open_,
                  getParentForChildren(),
                  isClean());
          open_ = null;
        }
        return openBuilder_;
      }

      // optional .mblock.Close close = 3;
      private com.alexkorovyansky.mblock.proto.MbLockCommands.Close close_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.alexkorovyansky.mblock.proto.MbLockCommands.Close, com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder, com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder> closeBuilder_;
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public boolean hasClose() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.Close getClose() {
        if (closeBuilder_ == null) {
          return close_;
        } else {
          return closeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public Builder setClose(com.alexkorovyansky.mblock.proto.MbLockCommands.Close value) {
        if (closeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          close_ = value;
          onChanged();
        } else {
          closeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public Builder setClose(
          com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder builderForValue) {
        if (closeBuilder_ == null) {
          close_ = builderForValue.build();
          onChanged();
        } else {
          closeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public Builder mergeClose(com.alexkorovyansky.mblock.proto.MbLockCommands.Close value) {
        if (closeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              close_ != com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance()) {
            close_ =
              com.alexkorovyansky.mblock.proto.MbLockCommands.Close.newBuilder(close_).mergeFrom(value).buildPartial();
          } else {
            close_ = value;
          }
          onChanged();
        } else {
          closeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public Builder clearClose() {
        if (closeBuilder_ == null) {
          close_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance();
          onChanged();
        } else {
          closeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder getCloseBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCloseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder getCloseOrBuilder() {
        if (closeBuilder_ != null) {
          return closeBuilder_.getMessageOrBuilder();
        } else {
          return close_;
        }
      }
      /**
       * <code>optional .mblock.Close close = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.alexkorovyansky.mblock.proto.MbLockCommands.Close, com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder, com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder> 
          getCloseFieldBuilder() {
        if (closeBuilder_ == null) {
          closeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.alexkorovyansky.mblock.proto.MbLockCommands.Close, com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder, com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder>(
                  close_,
                  getParentForChildren(),
                  isClean());
          close_ = null;
        }
        return closeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mblock.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mblock.Request)
  }

  public interface OpenOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code mblock.Open}
   */
  public static final class Open extends
      com.google.protobuf.GeneratedMessage
      implements OpenOrBuilder {
    // Use Open.newBuilder() to construct.
    private Open(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Open(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Open defaultInstance;
    public static Open getDefaultInstance() {
      return defaultInstance;
    }

    public Open getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Open(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Open_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Open_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexkorovyansky.mblock.proto.MbLockCommands.Open.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder.class);
    }

    public static com.google.protobuf.Parser<Open> PARSER =
        new com.google.protobuf.AbstractParser<Open>() {
      public Open parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Open(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Open> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Open parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alexkorovyansky.mblock.proto.MbLockCommands.Open prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mblock.Open}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alexkorovyansky.mblock.proto.MbLockCommands.OpenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Open_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Open_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alexkorovyansky.mblock.proto.MbLockCommands.Open.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Open.Builder.class);
      }

      // Construct using com.alexkorovyansky.mblock.proto.MbLockCommands.Open.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Open_descriptor;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Open getDefaultInstanceForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance();
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Open build() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Open result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Open buildPartial() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Open result = new com.alexkorovyansky.mblock.proto.MbLockCommands.Open(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alexkorovyansky.mblock.proto.MbLockCommands.Open) {
          return mergeFrom((com.alexkorovyansky.mblock.proto.MbLockCommands.Open)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alexkorovyansky.mblock.proto.MbLockCommands.Open other) {
        if (other == com.alexkorovyansky.mblock.proto.MbLockCommands.Open.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Open parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alexkorovyansky.mblock.proto.MbLockCommands.Open) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mblock.Open)
    }

    static {
      defaultInstance = new Open(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mblock.Open)
  }

  public interface CloseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code mblock.Close}
   */
  public static final class Close extends
      com.google.protobuf.GeneratedMessage
      implements CloseOrBuilder {
    // Use Close.newBuilder() to construct.
    private Close(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Close(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Close defaultInstance;
    public static Close getDefaultInstance() {
      return defaultInstance;
    }

    public Close getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Close(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Close_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Close_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexkorovyansky.mblock.proto.MbLockCommands.Close.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder.class);
    }

    public static com.google.protobuf.Parser<Close> PARSER =
        new com.google.protobuf.AbstractParser<Close>() {
      public Close parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Close(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Close> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Close parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alexkorovyansky.mblock.proto.MbLockCommands.Close prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mblock.Close}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alexkorovyansky.mblock.proto.MbLockCommands.CloseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Close_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Close_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alexkorovyansky.mblock.proto.MbLockCommands.Close.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Close.Builder.class);
      }

      // Construct using com.alexkorovyansky.mblock.proto.MbLockCommands.Close.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Close_descriptor;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Close getDefaultInstanceForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance();
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Close build() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Close result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Close buildPartial() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Close result = new com.alexkorovyansky.mblock.proto.MbLockCommands.Close(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alexkorovyansky.mblock.proto.MbLockCommands.Close) {
          return mergeFrom((com.alexkorovyansky.mblock.proto.MbLockCommands.Close)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alexkorovyansky.mblock.proto.MbLockCommands.Close other) {
        if (other == com.alexkorovyansky.mblock.proto.MbLockCommands.Close.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Close parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alexkorovyansky.mblock.proto.MbLockCommands.Close) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mblock.Close)
    }

    static {
      defaultInstance = new Close(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mblock.Close)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .mblock.Response.StatusCode status = 1;
    /**
     * <code>required .mblock.Response.StatusCode status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .mblock.Response.StatusCode status = 1;</code>
     */
    com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode getStatus();
  }
  /**
   * Protobuf type {@code mblock.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode value = com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexkorovyansky.mblock.proto.MbLockCommands.Response.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code mblock.Response.StatusCode}
     */
    public enum StatusCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 1;</code>
       */
      OK(0, 1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(1, 2),
      ;

      /**
       * <code>OK = 1;</code>
       */
      public static final int OK_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;


      public final int getNumber() { return value; }

      public static StatusCode valueOf(int value) {
        switch (value) {
          case 1: return OK;
          case 2: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
              public StatusCode findValueByNumber(int number) {
                return StatusCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusCode[] VALUES = values();

      public static StatusCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private StatusCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mblock.Response.StatusCode)
    }

    private int bitField0_;
    // required .mblock.Response.StatusCode status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode status_;
    /**
     * <code>required .mblock.Response.StatusCode status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .mblock.Response.StatusCode status = 1;</code>
     */
    public com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode getStatus() {
      return status_;
    }

    private void initFields() {
      status_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode.OK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alexkorovyansky.mblock.proto.MbLockCommands.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alexkorovyansky.mblock.proto.MbLockCommands.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mblock.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.alexkorovyansky.mblock.proto.MbLockCommands.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alexkorovyansky.mblock.proto.MbLockCommands.Response.class, com.alexkorovyansky.mblock.proto.MbLockCommands.Response.Builder.class);
      }

      // Construct using com.alexkorovyansky.mblock.proto.MbLockCommands.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode.OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.internal_static_mblock_Response_descriptor;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Response getDefaultInstanceForType() {
        return com.alexkorovyansky.mblock.proto.MbLockCommands.Response.getDefaultInstance();
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Response build() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alexkorovyansky.mblock.proto.MbLockCommands.Response buildPartial() {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Response result = new com.alexkorovyansky.mblock.proto.MbLockCommands.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alexkorovyansky.mblock.proto.MbLockCommands.Response) {
          return mergeFrom((com.alexkorovyansky.mblock.proto.MbLockCommands.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alexkorovyansky.mblock.proto.MbLockCommands.Response other) {
        if (other == com.alexkorovyansky.mblock.proto.MbLockCommands.Response.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alexkorovyansky.mblock.proto.MbLockCommands.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alexkorovyansky.mblock.proto.MbLockCommands.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .mblock.Response.StatusCode status = 1;
      private com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode status_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode.OK;
      /**
       * <code>required .mblock.Response.StatusCode status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .mblock.Response.StatusCode status = 1;</code>
       */
      public com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode getStatus() {
        return status_;
      }
      /**
       * <code>required .mblock.Response.StatusCode status = 1;</code>
       */
      public Builder setStatus(com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .mblock.Response.StatusCode status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = com.alexkorovyansky.mblock.proto.MbLockCommands.Response.StatusCode.OK;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mblock.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mblock.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mblock_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mblock_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mblock_Open_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mblock_Open_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mblock_Close_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mblock_Close_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mblock_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mblock_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/mblock/commands.proto\022\006mblock\"\204\001" +
      "\n\007Request\022\"\n\004type\030\001 \002(\0162\024.mblock.Request" +
      ".Type\022\032\n\004open\030\002 \001(\0132\014.mblock.Open\022\034\n\005clo" +
      "se\030\003 \001(\0132\r.mblock.Close\"\033\n\004Type\022\010\n\004OPEN\020" +
      "\001\022\t\n\005CLOSE\020\002\"\023\n\004Open\022\013\n\003key\030\001 \002(\t\"\024\n\005Clo" +
      "se\022\013\n\003key\030\001 \002(\t\"X\n\010Response\022+\n\006status\030\001 " +
      "\002(\0162\033.mblock.Response.StatusCode\"\037\n\nStat" +
      "usCode\022\006\n\002OK\020\001\022\t\n\005ERROR\020\002B2\n com.alexkor" +
      "ovyansky.mblock.protoB\016MbLockCommands"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mblock_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mblock_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mblock_Request_descriptor,
              new java.lang.String[] { "Type", "Open", "Close", });
          internal_static_mblock_Open_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mblock_Open_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mblock_Open_descriptor,
              new java.lang.String[] { "Key", });
          internal_static_mblock_Close_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_mblock_Close_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mblock_Close_descriptor,
              new java.lang.String[] { "Key", });
          internal_static_mblock_Response_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_mblock_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mblock_Response_descriptor,
              new java.lang.String[] { "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
